-- This migration is intentionally empty.
-- Migrations 0010–0013 were created manually without generating Drizzle snapshots,
-- so the snapshot was stuck at 0009 and db:generate kept regenerating those columns.
-- This file exists solely to bring the Drizzle snapshot up to date with the actual schema.