{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "questarr.fullname" . }}
  labels:
    {{- include "questarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.jwtSecret }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secret.igdbClientId }}
  IGDB_CLIENT_ID: {{ .Values.secret.igdbClientId | quote }}
  {{- end }}
  {{- if .Values.secret.igdbClientSecret }}
  IGDB_CLIENT_SECRET: {{ .Values.secret.igdbClientSecret | quote }}
  {{- end }}
{{- end }}
